name: build
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache JDK
        uses: actions/cache@v2
        with:
          path: ~/.jdk
          key: ${{ runner.os }}-jdk-${{ hashFiles('.jdkw', 'jdk-wrapper.sh') }}
      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: Setup for Build
        run: echo "TARGET=verify" >> $GITHUB_ENV
      - name: Setup for Release
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "TARGET=deploy -P release --settings settings.xml" >> $GITHUB_ENV
      - name: Run
        run: ./jdk-wrapper.sh ./mvnw clean ${TARGET} -P RPM -U -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Create Release
        id: create_github_release
        uses: actions/create-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset RPM
        uses: csexton/release-asset-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          pattern: "./target/rpm/kairosdb/RPMS/noarch/kairosdb*.rpm"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_github_release.outputs.upload_url }}
      - name: Upload Release Asset Tar.gz
        uses: csexton/release-asset-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          pattern: "./target/kairosdb*-bin.tgz"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_github_release.outputs.upload_url }}

# To Do:
# 1) Standard Github Actions upload release asset does not accept wildcards.
#    Doc: https://github.com/actions/upload-release-asset
#    Issue: https://github.com/actions/upload-release-asset/issues/47

